use_frameworks!

target 'LocationInputView_Example' do
  pod 'LocationInputView', :path => '../'

  target 'LocationInputView_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'

  end
end
